site_name: Generative Text
site_url: https://example.com/
theme:
  name: mkdocs
nav:
    - Home: index.md
    - GT-2: GT-2.md
    - GT-4: GT-4.md
    - GT-10: GT-10.md
    - GT-11: GT-11.md
    - GT-26: GT-26.md
