name: work-flow
on:
  push:
    branches:
      - main

jobs:
  update:
    name: Update markdowns
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Node install  
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: updater
        run: | 
          npm install mdmerge
          npm run mdmerge -o README.md project-description.md    
         
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}