name: work-flow
on:
  push:
    branches:
      - main

jobs:
  update:
    name: Update markdowns
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mdsaw
      - run: mdsaw -c gt-2/gt-2.md gt-4/gt-4.md README.md
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
