name: work-flow
on:
  push:
    branches:
      - main

jobs:
  update:
    name: Update markdowns
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Merger
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          >README.md
          cat project-description.md docs/index.md gt-2/README.md gt-4/README.md gt-10/README.md gt-11/README.md gt-26/README.md > README.md
          >docs/GT-2.md
          cat gt-2/README.md >> docs/GT-2.md
          >docs/GT-4.md
          cat gt-4/README.md >> docs/GT-4.md
          >docs/GT-10.md
          cat gt-10/README.md >> docs/GT-10.md
          >docs/GT-11.md
          cat gt-11/README.md >> docs/GT-11.md
          >docs/GT-26.md
          cat gt-26/README.md >> docs/GT-26.md
          git add .
          git commit -m "Update READMEs"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
         
  build:
    needs: update 
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}