name: work-flow
on:
  push:
    branches:
      - main

jobs:
  update:
    name: Update markdowns
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Pip install  
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: merger
        run: |
          pip install MarkdownTools 
          mdmerge -o /README.md /project-description.md
          mdmerge -o docs/gt-2.md gt-2/gt-2.md   
         
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}