name: work-flow
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Get README content from gt-2
        run: |
        cd gt-2
        GT2_README=$(cat README.md)
        cd ..

      - name: Update main README
        run: |
        echo "$GT2_README" > README.md
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README from gt-2
          commit_options: '--no-verify'
          branch: ${{ github.ref }}
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
