name: work-flow
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Update Readme  
        run: |
          git config --global user.email "emanuel.cohal@gmail.com"
          git config --global user.name "emanuelcohal"
          cat project-description.md >> README.md
          cat gt-2/gt-2.md >> README.md
          cat gt-4/gt-4.md >> README.md
          cat gt-10/gt-10.md >> README.md
          cat gt-11/gt-11.md >> README.md
          cat gt-26/gt-26.md >> README.md
          git add README.md
          git commit -m "Update README.md"
          git push origin main

      - name:Runner     
        run: |
          pip install markdown-include

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
